### ISSUE TITLE
Not running properly (Android 4.4.4)

### ISSUE THREAD

**Issue by TVUpbm** [MasterEric/WarpSpaceLiveWallpaper#1]
Also posted in the Reddit thread.

It seems to be only working on the farthest left side of my screen? And the app crashes whenever I hit the settings button. Also, it feels kinda slow.

Moto X 2013 (1st Edition). Android 4.4.4.

*But, on the left side of my screen, it looks great? OH, and by that I mean when I swipe all the way to the left on my home screen, not like, the left half of the screen or anything.

**Comment by EliteMasterEric** [comment]
The issue has been patched in the newest version (v0.2)
