### ISSUE TITLE
Doesn't seem to want to be set?

### ISSUE THREAD

**Issue by DeadlySprinklez** [MasterEric/WarpSpaceLiveWallpaper#2]
I run Android 4.4.5 I believe, and it doesn't show up. Like, it's just a complete black screen, but it seems to be fine in the preview. Also, whenever I hit settings, both of the apps crash. Just thought I should point it out.

**Comment by EliteMasterEric** [comment]
Someone else had a kinda similar problem.

Try scrolling all the way to the left home screen, does it display fine there?

**Comment by EliteMasterEric** [comment]
The problem has been patched in the latest version (v0.2)
